services:
  db:
    image: postgres:16-alpine
    container_name: janitor_pg_db
    restart: always
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_LOCAL_USER}
      - POSTGRES_PASSWORD=${POSTGRES_LOCAL_PASSWORD}
    volumes:
      - local_pgdata:/var/lib/postgresql/data
    networks:
      - app-networks
    env_file:
      - .env

  web: 
    image: ghcr.io/oddsteam/odds-janitor:latest
    container_name: janitor_web_rails
    depends_on:
      - db
    command: bash -c "rm -f tmp/pids/server.pid && bundle install && bundle exec rails db:migrate && bundle exec rails s -b '0.0.0.0'"
    environment:
      - RAILS_ENV=${RAILS_ENV}
    ports:
      - "82:3000"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - app-networks
      
volumes:
  local_pgdata: {}

networks:
  app-networks:


  